In [4]:
import sympy as sp


r,r0,zeta = sp.symbols('r r_0 zeta',real = True)

phi_ = sp.Function('phi')(r)
phi_ = sp.Integer(1)/sp.Integer(2)* (1-sp.tanh(2/zeta*sp.Abs(r-r0)))
sp.simplify(sp.diff(phi_,r))

Piecewise((0, Eq(r, r_0)), (-(r - r_0)/(zeta*cosh(2*Abs(r - r_0)/zeta)**2*Abs(r - r_0)), True))

<img src = 'symbolic_calculations_images/image1.png'>

<img src = 'symbolic_calculations_images/paper_E106_collision.png'>

<img src = 'symbolic_calculations_images/paper_E106_dynamics.png'>

<img src = 'symbolic_calculations_images/paper_E106_field_phi.png'>

<img src = 'symbolic_calculations_images/paper_E106_mu_1.png'>

a = 0.001, b = 0.550, and $\epsilon$ = 0.0152
<br>$\tau_3$ = 1.000 and $\tau_4$ =  1.500 </br>
<br>
$\gamma$ = 1 and $\gamma$ =  0.05.
</bt>

In [ ]:
# hello,professor ,i was looking into this paper was trying to replicate the some of the r                                                                                                                                                                             esults from the paper and i have a doubt in Table1 its shows the feq functions and modified collision function in that  for k =4 S has a F term which is given (ref eq -13) and phi is give as (ref eq -11) now we also calculate phi so will the give the same result and to calculate gradient which method to use central or forward/backward.


In [6]:
import numpy as np

In [7]:
f = lambda x,n: 4*n**2/((n**2-4)*x)


In [8]:
theta2t1 = np.array([270.9,276.9,268.9]) 
theta1t1 = np.array([247.68,250.49,251.79]) 

theta2t2 = np.array([90.44,87.5,86.83,]) 
theta1t2 = np.array([67.33,70.51,71.39]) 

thetap1 = (theta2t1-theta1t1)/2
thetap2 = (theta2t2-theta1t2)/2

theta = (thetap1+thetap2)/2
lam1 = 3.33 * np.sin(theta*(np.pi/180)) * 10
lam1

array([6.68593129, 6.2683404 , 4.71358738])

In [9]:
theta2t1 = np.array([282.8,276.4,274.4]) 
theta1t1 = np.array([234.49,242.2,243.88]) 

theta2t2 = np.array([102.8,96.2,94.61])
theta1t2 = np.array([54.04,61.84,63.8]) 

thetap1 = (theta2t1-theta1t1)/2
thetap2 = (theta2t2-theta1t2)/2

theta = (thetap1+thetap2)/2
lam2 = 3.33 * np.sin(theta*(np.pi/180)) * 10 * 0.5
lam2

array([6.8431053 , 4.90688026, 4.40259525])

In [10]:
a1 = f(lam1,np.array([3,4,5]))
a2 = f(lam2,np.array([3,4,5]))

a1,a2

(array([1.07688812, 0.85083658, 1.01025066]),
 array([1.05215391, 1.08690921, 1.08161311]))

In [11]:
a1[1] +=.2

In [12]:
a1

array([1.07688812, 1.05083658, 1.01025066])

In [13]:
r = (a1+a2).sum()/6
(r-1.097)/1.097

np.float64(-0.0339332120467813)

In [14]:
r * 6

np.float64(6.358651598308086)

In [15]:
a1 = f(lam1,np.array([3,4,5]))


In [16]:
theta2 = np.array([282.8,276.4,274.4]) 
theta1 = np.array([234.49,242.2,243.88]) 

thetap1 = (theta2-theta1)/2


In [17]:
theta2 = np.array([102.8,96.2,94.61]) 
theta1 = np.array([54.04,61.84,63.8]) 

thetap2 = (theta2-theta1)/2


In [18]:
theta = (thetap1 + thetap2)/2

In [19]:
theta

array([24.2675, 17.14  , 15.3325])

In [20]:
lam = 3.33 * np.sin(theta*(np.pi/180)) * .5 * 10

In [21]:
f = lambda x,n: 4*n**2/((n**2-4)*x)

In [22]:
a2 = f(lam,np.array([3,4,5]))

In [23]:
a1[1] += 1

In [24]:
a1

array([1.07688812, 1.85083658, 1.01025066])

In [25]:
r = (a1.sum()+ a2.sum())/6

In [26]:
(1.0689-1.097)/1.097

-0.025615314494074764